# Site Settings
title: Cay crew
email: nguyen.chiencong@gmail.com
tagline: Wisdom to make a game.
description: >
  We make games and art.
baseurl: ""
url: "https://caycrew.art"
github_username:  nguyenchiencong
# Build Settings
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM